# This pipeline syncs the code from GitLab to GitHub automatically.

stages:
  - deploy

sync_to_github:
  stage: deploy
  image: alpine:latest  # Using a lightweight Docker image

  before_script:
    - apk add --no-cache git  # Installing Git in the runner

  script:
    # Adding the GitHub repository as a remote.
    # The URL uses your GitHub username (Keshab1997), the GITHUB_TOKEN variable,
    # and your repository name (Study-With-Keshab).
    - git remote add github https://Keshab1997:$GITHUB_TOKEN@github.com/Keshab1997/Study-With-Keshab.git

    # Forcefully pushing all changes from the current GitLab branch to the same branch on GitHub.
    # The '-f' flag ensures that the GitHub repo exactly mirrors the GitLab repo.
    - git push -f github HEAD:$CI_COMMIT_REF_NAME

  only:
    - main  # This job will only run for commits on the 'main' branch.